#version: '3.8'

services:
  nginx:
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
      - "80:80"
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/index.php"]
      interval: 10s
      timeout: 3s
      retries: 3

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--silent",
          "-h127.0.0.1",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge

