#version: '3.8'

services:
  nginx:
    container_name: nginx
    user: nginxuser
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
      - "80:80"
    build: ./requirements/nginx
    env_file: .env
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    # read_only: true

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build: ./requirements/wordpress
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/index.php"]
      interval: 10s
      timeout: 3s
      retries: 3

  mariadb:
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: ./requirements/mariadb
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-hlocalhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge

